### ISSUE TITLE
Support linters for Open Policy Agent and Rego

### ISSUE THREAD

**Issue by yu-iskw** [trunk-io/plugins#670]
## Motivation

It would be awesome to support linters and formatters for Open Policy Agent and Rego. For example, `regal` is a linter for Rego. 

https://github.com/StyraInc/regal

**Comment by TylerJang27** [comment]
Hi @yu-iskw, thanks for the suggestion! From an initial audit, it looks like it will be fairly straightforward to integrate `regal` into Trunk. You're welcome to take a stab at it yourself, since all of our definitions in this repo are open source, but if not we will look into getting it integrated in the near future.

**Comment by TylerJang27** [comment]
I just landed a `regal` linter and `opa` formatter. They'll both be included in the next release, but if you want to start using them now, you can change your `ref` for plugins to be `ca2abe103a0dcea2f61c7bd7c322bf619334765e`!

**Comment by yu-iskw** [comment]
@TylerJang27 Thank you for immediately supporting them. I will try to add other linters by myself next time referring to the pull requests.
