### ISSUE TITLE
Support standard paths to config files of linters

### ISSUE THREAD

**Issue by yu-iskw** [trunk-io/plugins#714]
## Motivation

Config files of linters are located at the path specialized to trunk.io under `.trunk/configs`. Some extensions or plugins of IDEs as VS code and IntelliJ don't recognize the config files, because those expect the default location of each linter. We can use a function to format code on IDE with config files using extensions and plugins. If we can seamlessly share or synchronize config files between Trunk and IDE, that would be awesome.

### Plan 1: Use symbolic links between paths for Trunk and default paths

I usually create some symbolic links to make Trunk and the IDE recognize. If I already have a config file of a linter before introducing Trunk, I create a symbolic link from the existing file in `.trunk/configs`. On the contrary, if I first introduce a new linter by Trunk, I create the symbolic link to the default path which the linter expects. We can also implement a sub command to manage symbolic links between Trunk and default paths of linters.

### Plan 2: Trunk tris to load a config file of a linter from the default path

As far as I know, we define paths of config files so that Trunk can load. For instance, the default config path of `autopep8` in Trunk is `.pep8`.  We can also make Trunk load config files from default paths of linters.

https://github.com/trunk-io/plugins/blob/2f51ee585d42177b667557f4b48e45acf6e38294/linters/autopep8/plugin.yaml#L25

**Comment by TylerJang27** [comment]
Hi @yu-iskw! Thanks for the suggestion. I'd like to explain a bit more about how our linter config loading works and hear more about your use case.

So the way [linter configs](https://docs.trunk.io/check/configuration#moving-linter-configs) work today is:
1. We respect any configuration that a linter automatically inherits. For example, if a linter expects its config file to be in the root of your repo, or your home folder, it will continue to function in that way.
2. If you have a relevant config file in `.trunk/configs`, we will symlink it into the sandbox root when performing linter execution. This only happens in the sandbox to avoid cluttering your workspace.
3. If you're enabling a new linter, and we have a recommended, formatter-friendly config file, we will automatically create it in `.trunk/configs`. That's not a requirement, just a convenience that we offer to avoid cluttering the root of your workspace.

In that sense, we already support plan 2, if I understand your suggestion correctly. A config file can be located in `.` or `.trunk/configs`, but we [recommend](https://docs.trunk.io/check/configuration#moving-linter-configs) symlinking/moving it to the repo root for individual extensions.

---

I personally prefer plan 1 on a case by case basis, although I don't think that's something we'd want Trunk to do automatically. I'm curious to hear more about your perspective and how many linter configs you've had to do this for; usually we only have linter configs in the repo root for eslint and for any build tools, since the [Trunk VSCode extension](https://marketplace.visualstudio.com/items?itemName=Trunk.io) can take the place of most other linter extensions.
